##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: crediYaAutenticacion
  devtools:
    add-properties: false
  profiles:
    include:

adapters:
  r2dbc:
    host: "localhost"
    port: 3306
    database: "autenticacion"
    username: "app_user"
    password: "juan*201"
